version: '3.8'

services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    networks:
      - laravel

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - /home/abdoulaye/Documents/GestionPresenceLaravel/storage/app/firebase/firebase_credentials.json:/var/www/firebase_credentials.json # Mapping du fichier Firebase
    networks:
      - laravel
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: laraveluser
      PMA_PASSWORD: password
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
